export const FETCH_RENTALS_START = 'FETCH_RENTALS_START';
export const FETCH_RENTALS_SUCCESS = 'FETCH_RENTALS_SUCCESS';
export const FETCH_RENTALS_FAIL = 'FETCH_RENTALS_FAIL';

export const CREATE_RENTAL_START = 'CREATE_RENTAL_START';
export const CREATE_RENTAL_SUCCESS = 'CREATE_RENTAL_SUCCESS';
export const CREATE_RENTAL_FAIL = 'CREATE_RENTAL_FAIL';

export const DELETE_RENTAL_START = 'DELETE_RENTAL_START';
export const DELETE_RENTAL_SUCCESS = 'DELETE_RENTAL_SUCCESS';
export const DELETE_RENTAL_FAIL = 'DELETE_RENTAL_FAIL';

export const UPDATE_RENTAL_START = 'UPDATE_RENTAL_START';
export const UPDATE_RENTAL_SUCCESS = 'UPDATE_RENTAL_SUCCESS';
export const UPDATE_RENTAL_FAIL = 'UPDATE_RENTAL_FAIL';

export const RENTAL_CONSUME_SUCCESS = 'RENTAL_CONSUME_SUCCESS';
export const RENTAL_CONSUME_ERROR = 'RENTAL_CONSUME_ERROR';
