export const LOGIN_CONSUME_ERROR = 'LOGIN_CONSUME_ERROR';
export const LOGIN_CONSUME_SUCCESS = 'LOGIN_CONSUME_SUCCESS';

export const LOGIN_START = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
