export const REGISTER_START = 'REGISTER_START';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_CONSUME_ERROR = 'REGISTER_CONSUME_ERROR';
export const REGISTER_CONSUME_SUCCESS = 'REGISTER_CONSUME_SUCCESS';
