export const REGISTER_START = 'REGISTER_START';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR_ALERT_CLOSE = 'REGISTER_ERROR_ALERT_CLOSE';
export const REGISTER_SUCCESS_ALERT_CLOSE = 'REGISTER_SUCCESS_ALERT_CLOSE';
